### ISSUE TITLE
Import js SDK instead of copying the code

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-uniapp-sdk#3]
See: https://github.com/casdoor/casdoor-vue-sdk/blob/0c3fb89c9d654e22c6e1d323bd9ff002a3a7e6d1/package.json#L15

**Comment by hsluoyz** [comment]
@Beacontownfc

**Comment by Beacontownfc** [comment]
The new PR (https://github.com/casdoor/casdoor-uniapp-sdk/pull/4) has solved this problem.
